#services:
#  mysql:
#    container_name: mysql
#    image: mysql:8.0
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: shopee
#      MYSQL_USER: sa
#      MYSQL_PASSWORD: Thuan@417
#    volumes:
#      - mysql_data:/var/lib/mysql
#    ports:
#      - "3306:3306"
#    command: --default-authentication-plugin=mysql_native_password
#    networks:
#      - shopee-network
#
#  zookeeper:
#    container_name: zookeeper
#    image: bitnami/zookeeper:3.9-debian-12
#    ports:
#      - "2181:2181"
#    volumes:
#      - "zookeeper_data:/bitnami"
#    environment:
#      - ALLOW_ANONYMOUS_LOGIN=yes
#    networks:
#      - shopee-network
#
#  kafka:
#    container_name: kafka
#    image: bitnami/kafka:3.8-debian-12
#    ports:
#      - "9092:9092"
#    expose:
#      - "9093"
#    volumes:
#      - "kafka_data:/bitnami"
#    environment:
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#      - ALLOW_PLAINTEXT_LISTENER=yes
#      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka:9093,OUTSIDE://localhost:9092
#      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
#      - KAFKA_LISTENERS=INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
#      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
#    depends_on:
#      - zookeeper
#    networks:
#      - shopee-network
#
#  kafka-ui:
#    container_name: kafka-ui
#    image: provectuslabs/kafka-ui:latest
#    ports:
#      - "9090:8080"
#    restart: always
#    environment:
#      - KAFKA_CLUSTERS_0_NAME=local
#      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9093
#      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
#    networks:
#      - shopee-network
#
#  redis:
#    container_name: redis
#    image: redis:latest
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis_data:/data
#    networks:
#      - shopee-network
#
#volumes:
#  zookeeper_data:
#    driver: local
#  kafka_data:
#    driver: local
#  mysql_data:
#    driver: local
#  redis_data:
#    driver: local
#
#networks:
#  shopee-network:
#    driver: bridge

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopee
      MYSQL_USER: sa
      MYSQL_PASSWORD: Thuan@417
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks: [shopee-network]

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1   # ZK ổn định
    container_name: zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: "2181"
      ZOOKEEPER_TICK_TIME: "2000"
    ports:
      - "2181:2181"
    networks: [shopee-network]

  kafka:
    image: confluentinc/cp-kafka:7.6.1       # Kafka ổn định
    container_name: kafka
    restart: unless-stopped
    depends_on: [zookeeper]
    environment:
      KAFKA_BROKER_ID: "1"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"

      # 2 listener: nội bộ & ngoài máy
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://PUBLIC_IP:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      # Single-node defaults
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"
    ports:
      - "9092:9092"   # internal (các container + kafka-ui)
      - "9094:9094"   # external (client ngoài VPS)
    networks: [shopee-network]

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: unless-stopped
    depends_on: [kafka]
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    ports:
      - "9090:8080"
    networks: [shopee-network]

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks: [shopee-network]

volumes:
  zookeeper_data:
  kafka_data:
  mysql_data:
  redis_data:

networks:
  shopee-network:
    driver: bridge
